// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("CalculatorLib")]
[assembly: AssemblyProductAttribute("Modules.Core")]
[assembly: AssemblyDescriptionAttribute("Modules with interchangeable source mode and binary mode")]
[assembly: AssemblyVersionAttribute("1.0")]
[assembly: AssemblyFileVersionAttribute("1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0";
    }
}
